apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: library-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007