apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: library_user
  POSTGRES_PASSWORD: library_pass
  POSTGRES_DB: library_db
  DATABASE_URL: postgresql://library_user:library_pass@postgres-service:5432/library_db